version: "3.5"
services:
  mongo:
    container_name: mongo_dev
    image: mongo:latest
    environment:
      MONGO_INITDB_NAME: tasker
    ports:
      - 27017:27017
    networks:
      - dev
  mongo_seed:
    container_name: mongo_seed
    build: .
    networks:
      - dev
    depends_on:
      - mongo
  app:
    image: golang:1.13.5-alpine
    volumes:
      - .:/go/src/task-scheduler
    ports:
      - 3000:3000
    working_dir: /go/src/task-scheduler
    command: go run main.go
    networks:
      - dev
    environment:
      MONGO_URL: mongo_dev:27017
      CGO_ENABLED: 0
networks:
  dev:
    driver: bridge
