POST http://localhost:3000/task
Content-Type: application/json

{
    "priority":"high",
    "skills":["skill1", "skill3"]
}

###

#Begin a task
PUT http://localhost:3000/task/begin/5df863f2e008ea635921f12c

###


#Complete a task
PUT http://localhost:3000/task/complete/5df7e79724600682f989bd60

###


###
#Create task with no skills defined for the task should fail
POST http://localhost:3000/task
Content-Type: application/json

{
  "id": "1",
  "priority":"high",
  "skills":[]
}

###
#Low priority task
POST http://localhost:3000/task
Content-Type: application/json

{
  "priority":"low",
  "skills":["skill1", "skill2"]
}

###

POST http://localhost:3000/task
Content-Type: application/json

{
    "id": "1",
    "priority":"high", 
    "skills":[]
}

###

#Complete the task
PUT http://localhost:3000/task/complete/5df7c32177661b81e434f888

###

GET http://localhost:3000/agents

###
