DROP DATABASE IF EXISTS tasker CASCADE;

CREATE DATABASE IF NOT EXISTS tasker;

SET DATABASE = tasker;

CREATE TABLE IF NOT EXISTS tasks (
     taskId SERIAL NOT NULL PRIMARY KEY,
     skills VARCHAR NOT NULL UNIQUE,
     priority VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS agents (
     agentId SERIAL NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS skills (
    skillId SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS skillmapping (
      skillMapId SERIAL NOT NULL PRIMARY KEY,
      agentId VARCHAR NOT NULL UNIQUE
);



