DROP DATABASE IF EXISTS tasker CASCADE;

CREATE DATABASE IF NOT EXISTS tasker;

SET DATABASE = tasker;

CREATE TABLE IF NOT EXISTS tasks (
     id SERIAL NOT NULL PRIMARY KEY,
     skills VARCHAR NOT NULL UNIQUE,
     priority VARCHAR NOT NULL UNIQUE
);
